__version__ = "0.1"


AUDIO_EXTENSIONS = {
    ".aac",
    ".aiff",
    ".alac",
    ".amr",
    ".ape",
    ".au",
    ".flac",
    ".m4a",
    ".m4b",
    ".mid",
    ".midi",
    ".mp2",
    ".mp3",
    ".ogg",
    ".opus",
    ".ra",
    ".wav",
    ".wma",
}

LANGUAGE_OPTIONS = {
    "English": "en",
    "Russian": "ru",
    "中文": "zh",
}

TRANSLATIONS: dict[str, dict] = {
    "en": {
        "window_title": "audio2ogg",
        "tab_converter": "Converter",
        "tab_log": "Log",
        "tab_settings": "Settings",
        "tab_help": "Help",
        "settings_frame_title": "Application settings",
        "language_label": "Language:",
        "output_dir_label": "Output folder:",
        "choose_button": "Choose...",
        "drop_frame_title": "Drag and drop audio files here",
        "add_files_button": "Add files",
        "remove_selected_button": "Remove selected",
        "clear_list_button": "Clear list",
        "convert_button": "Convert to OGG",
        "ffmpeg_found": "ffmpeg found: {path}",
        "ffmpeg_missing_log": "ffmpeg not found (neither bundled nor in PATH).",
        "ffmpeg_missing_title": "ffmpeg not found",
        "ffmpeg_missing_message": (
            "Could not find ffmpeg executable.\n\n"
            "For portable builds ffmpeg must be embedded in the app.\n"
            "For development runs install ffmpeg and add it to PATH."
        ),
        "pick_audio_title": "Select audio files",
        "audio_files_filter": "Audio files",
        "log_added_files": "Added files: {count}",
        "log_skipped_items": "Skipped items: {count}",
        "log_removed_files": "Removed files: {count}",
        "log_list_cleared": "List cleared.",
        "no_files_title": "No files",
        "no_files_message": "Add files before conversion.",
        "error_title": "Error",
        "ffmpeg_not_found_short": "ffmpeg not found (neither bundled nor in PATH).",
        "log_start_conversion": "Starting conversion. Files: {count}",
        "log_converting": "Converting: {src} -> {dst}",
        "log_ok": "OK: {name}",
        "log_error_unknown": "Unknown ffmpeg error.",
        "log_error": "ERROR: {name} | {err}",
        "log_done": "Done. Successful: {ok}, failed: {failed}",
        "language_switched": "Language switched to English.",
        "help_shortcuts_title": "Keyboard shortcuts",
        "help_shortcuts": [
            ("Ctrl+O",     "Add files"),
            ("Ctrl+A",     "Select all in list"),
            ("Delete",     "Remove selected"),
            ("Escape",     "Deselect all"),
            ("Ctrl+Enter", "Start conversion"),
            ("Ctrl+L",     "Clear list"),
        ],
        "help_note": "Shortcuts work regardless of keyboard layout.",
        "open_folder_button": "Open folder",
        "done_title": "Conversion complete",
        "changelog_title": "Changelog",
        "changelog_button": "Changelog",
    },
    "ru": {
        "window_title": "audio2ogg",
        "tab_converter": "Конвертер",
        "tab_log": "Лог",
        "tab_settings": "Настройки",
        "tab_help": "Справка",
        "settings_frame_title": "Настройки приложения",
        "language_label": "Язык:",
        "output_dir_label": "Папка экспорта:",
        "choose_button": "Выбрать...",
        "drop_frame_title": "Перетащите аудиофайлы сюда",
        "add_files_button": "Добавить файлы",
        "remove_selected_button": "Удалить выбранные",
        "clear_list_button": "Очистить список",
        "convert_button": "Конвертировать в OGG",
        "ffmpeg_found": "ffmpeg найден: {path}",
        "ffmpeg_missing_log": "ffmpeg не найден (ни встроенный, ни в PATH).",
        "ffmpeg_missing_title": "ffmpeg не найден",
        "ffmpeg_missing_message": (
            "Не найден исполняемый файл ffmpeg.\n\n"
            "Для portable-версии ffmpeg должен быть встроен в сборку.\n"
            "Для dev-запуска установите ffmpeg и добавьте его в PATH."
        ),
        "pick_audio_title": "Выберите аудиофайлы",
        "audio_files_filter": "Аудиофайлы",
        "log_added_files": "Добавлено файлов: {count}",
        "log_skipped_items": "Пропущено элементов: {count}",
        "log_removed_files": "Удалено файлов: {count}",
        "log_list_cleared": "Список очищен.",
        "no_files_title": "Нет файлов",
        "no_files_message": "Сначала добавьте файлы для конвертации.",
        "error_title": "Ошибка",
        "ffmpeg_not_found_short": "ffmpeg не найден (ни встроенный, ни в PATH).",
        "log_start_conversion": "Запуск конвертации. Файлов: {count}",
        "log_converting": "Конвертация: {src} -> {dst}",
        "log_ok": "OK: {name}",
        "log_error_unknown": "Неизвестная ошибка ffmpeg.",
        "log_error": "ERROR: {name} | {err}",
        "log_done": "Готово. Успешно: {ok}, с ошибками: {failed}",
        "language_switched": "Язык переключен на русский.",
        "help_shortcuts_title": "Горячие клавиши",
        "help_shortcuts": [
            ("Ctrl+O",     "Добавить файлы"),
            ("Ctrl+A",     "Выделить все в списке"),
            ("Delete",     "Удалить выделенные"),
            ("Escape",     "Снять выделение"),
            ("Ctrl+Enter", "Запустить конвертацию"),
            ("Ctrl+L",     "Очистить список"),
        ],
        "help_note": "Горячие клавиши работают на любой раскладке.",
        "open_folder_button": "Открыть папку",
        "done_title": "Конвертация завершена",
        "changelog_title": "История изменений",
        "changelog_button": "История изменений",
    },
    "zh": {
        "window_title": "audio2ogg",
        "tab_converter": "转换器",
        "tab_log": "日志",
        "tab_settings": "设置",
        "tab_help": "帮助",
        "settings_frame_title": "应用设置",
        "language_label": "语言：",
        "output_dir_label": "输出文件夹：",
        "choose_button": "选择...",
        "drop_frame_title": "将音频文件拖放到此处",
        "add_files_button": "添加文件",
        "remove_selected_button": "删除所选",
        "clear_list_button": "清空列表",
        "convert_button": "转换为 OGG",
        "ffmpeg_found": "已找到 ffmpeg：{path}",
        "ffmpeg_missing_log": "未找到 ffmpeg（既无内置版本，也不在 PATH 中）。",
        "ffmpeg_missing_title": "未找到 ffmpeg",
        "ffmpeg_missing_message": (
            "找不到 ffmpeg 可执行文件。\n\n"
            "便携版应用需要将 ffmpeg 内置于程序中。\n"
            "开发模式下请安装 ffmpeg 并将其添加到 PATH。"
        ),
        "pick_audio_title": "选择音频文件",
        "audio_files_filter": "音频文件",
        "log_added_files": "已添加文件：{count}",
        "log_skipped_items": "已跳过项目：{count}",
        "log_removed_files": "已删除文件：{count}",
        "log_list_cleared": "列表已清空。",
        "no_files_title": "无文件",
        "no_files_message": "请先添加要转换的文件。",
        "error_title": "错误",
        "ffmpeg_not_found_short": "未找到 ffmpeg（既无内置版本，也不在 PATH 中）。",
        "log_start_conversion": "开始转换，文件数：{count}",
        "log_converting": "正在转换：{src} -> {dst}",
        "log_ok": "成功：{name}",
        "log_error_unknown": "未知的 ffmpeg 错误。",
        "log_error": "错误：{name} | {err}",
        "log_done": "完成。成功：{ok}，失败：{failed}",
        "language_switched": "语言已切换为中文。",
        "help_shortcuts_title": "快捷键",
        "help_shortcuts": [
            ("Ctrl+O",     "添加文件"),
            ("Ctrl+A",     "全选列表"),
            ("Delete",     "删除所选"),
            ("Escape",     "取消选择"),
            ("Ctrl+Enter", "开始转换"),
            ("Ctrl+L",     "清空列表"),
        ],
        "help_note": "快捷键在任何键盘布局下均可使用。",
        "open_folder_button": "打开文件夹",
        "done_title": "转换完成",
        "changelog_title": "更新日志",
        "changelog_button": "更新日志",
    },
}
